Rails views
Oleg-Y-Novikov/TestGuru pull request #7
Opened 2022-07-27 10:14 UTC by Oleg-Y-Novikov

2022-07-27 14:37 UTC, VidgarVii requested changes

2022-07-27 14:37 UTC, VidgarVii commented on app/controllers/questions_controller.rb
>    before_action :find_test, only:     %i[index new create]
важно:
ТЗ: "Список вопросов теста должен выводиться **на той же странице, что и сам тест**"
другими словами нужна страница для вывода теста
что приводит к следующим выводам:
- экшен `index` в классе `QuestionsController` лишний
- вызов коллбека для `index` не нужен
- список вопросов нужно выводить на странице теста
- путь `test_questions_path`, который ты используешь в экшенах, тоже лишний (нужно отменить его создание в `routes`)
- нужен контроллер для ресурса `:tests` (его написание было поэтапно продемонстрировано в скринкасте)

2022-07-27 14:37 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +    Date.today.year
в рельсах рекомендуется использовать `Time.current` вместо `Time.now` (`Time.new`) и `Date.current` вместо `Date.today`
`.current` возвращает текущий момент времени с учетом настройки часового пояса в приложении

2022-07-27 14:37 UTC, VidgarVii commented on app/views/layouts/_footer.html.erb
> +    <a href=<%= github_url('Oleg-Y-Novikov', 'TestGuru') %> target="_blank" rel="noopener nofollow">TestGuru</a>
используй `link_to` внутри хэлпера, а здесь просто вызывай его: `<%= github_url('name', 'test_guru') %>`
текст ссылки `TestGuru` можно также передавать третьим параметром в хэлпер
возможно имеет смысл сделать [keyword arguments](https://robots.thoughtbot.com/ruby-2-keyword-arguments): `<%= github_url(author: 'name', repo: 'test_guru', title: 'TestGuru') %>

2022-07-27 14:37 UTC, VidgarVii commented on app/views/layouts/_footer.html.erb
> +    <a href="https://vk.com/o.l.e.g.novikov/" target="_blank" rel="noopener nofollow">Oleg Novikov</a>
тут так же можно использовать хелпер link_to

2022-07-29 05:59 UTC, BubuntuClu requested changes

2022-07-29 05:59 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +  before_action :find_user, only: %i[create]
нужно ли выносить в колбэк метод, который используется в одном экшене? почему бы просто внутри `create` не найти пользователя?

2022-07-29 05:59 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +  def question_header(test_title)
ориентируйся на состояние объекта, а не наэкшен, который приходит. передавай сюда сам объект вопроса и через `new_record?/persisted?` определяй какой заголовок подставит

2022-07-29 05:59 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +  def correct_url
это что-то лишнее. почему ссылка пустая если нет теста?
тебе нужно использовать структуру `form_with model: [@parent, @child]`, которая сам будет управлять роутингом в зависимости от наличия объектов

2022-07-29 05:59 UTC, BubuntuClu commented on app/helpers/tests_helper.rb
> +  def test_header
тоже надо сделать через состояние объекта

2022-07-29 05:59 UTC, BubuntuClu commented on app/models/test.rb
> +  validates_numericality_of :level, only_integer: true, greater_than_or_equal_to: 0,
различные валидации типа `validates_...` это старые валидации. лучше переписать все на `validates` через доп опции

2022-07-29 05:59 UTC, BubuntuClu commented on app/views/questions/_question.html.erb
> +  <% if action_name == 'show' &&  controller_name == 'questions' %>
не стоит выносить такое во вьюхи. если нужно разное поведение, то делай разные вьюхи под это

2022-08-03 09:50 UTC, merged